
#
# Example: 
# These will be filled in automatically by core (based on diploi-template.yaml)
#

stage: development

images:
  app: registry-docker-registry.registry/myfirstdeploiment/app:latest

hosts:
  app: xxx.diploinetes.nemesys.fi

storage:
  - label: app
    hostPath: /storage/d11111/volume-app
    sizeMB: 8000
  - label: rootpersist
    hostPath: /storage/d11111/volume-root-persist
    sizeMB: 1000

parameterGroups:
  mysql:
    enabled: false,
    parameters:
      DB_HOST: mysql,
      DB_DB_PASSWORD: pw

env: 
  - name: SMTP_HOST
    value: somehost.someplace.net
    selector: label=app
  - name: SMTP_PASSWORD
    value: xyz
    selector: label=app

sshInternalProxyPublicKey: xxxx

repository:
  url: https://github.com/MarcusAhlfors/myservice
  branch: main

git: 
  userName: info@diploi.dev
  userEmail: Diploi User




