apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: '/'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  tls:
    - hosts:
        - {{ .Values.hosts.app }}
      secretName: tls-secret
  rules:
    - host: {{ .Values.hosts.app }}
      http:
        paths:
          - path: '/'
            pathType: Prefix
            backend:
              serviceName: app
              servicePort: 80
              #service: (This is for newer kubernetes?)
              #  name: {{ .Values.label }}
              #  port:
              #    number: 80
